services:
  # Base de datos MySQL
  - type: pserv
    name: mysql-db
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: hospital
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        sync: false

  # API de Datos (PHP)
  - type: web
    name: datos-api
    env: docker
    dockerfilePath: ./datos/Dockerfile
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: hospital
      - key: DB_USER
        value: root
      - key: DB_PASSW
        sync: false
      - key: KEY
        sync: false
      - key: TOKEN
        sync: false

  # API de Negocio (PHP)
  - type: web
    name: negocio-api
    env: docker
    dockerfilePath: ./negocio/Dockerfile
    envVars:
      - key: DATOS_API_URL
        fromService:
          type: web
          name: datos-api
          property: host
      - key: KEY
        sync: false
      - key: TOKEN
        sync: false

  # Frontend (Angular)
  - type: web
    name: presentacion-web
    env: docker
    dockerfilePath: ./presentacion/hvpresentacion/Dockerfile
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: negocio-api
          property: host

databases:
  - name: mysql-data
    databaseName: hospital
    user: root
